bugfix: allow only one `public_sub_value_target` per challenge (#1476)
Recursively verifying mozak starks fails with:

```
---- stark::recursive_verifier::tests::recursive_verify_mozak_starks stdout ----
thread 'stark::recursive_verifier::tests::recursive_verify_mozak_starks' panicked at /Users/bing/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itertools-0.12.1/src/zip_eq_impl.rs:50:17:
itertools: .zip_eq() reached end of one iterator before the other
```

because we have a mismatch in the number of targets per challenge. This
PR addresses that.

---------

Co-authored-by: Matthias Görgens <matthias.goergens@gmail.com>